mwc integration
cypherstack/stack_wallet pull request #1016
Opened 2024-11-13 09:03 UTC by vekamo

2025-03-31 19:24 UTC, julian-CStack requested changes
Partial review

2025-09-03 17:07 UTC, sneurlax commented on lib/models/isar/stack_theme.dart
Resolved by 3442aab0dcfa0d16fe9dec57d0035b1f21522b54 but not on this remote.

2025-09-03 17:07 UTC, sneurlax commented on lib/db/migrate_wallets_to_isar.dart
Resolved by 62f111ea85fd48ecca7f16e0f6b4cdb7a6e7457c but not on this remote.

2025-09-03 17:08 UTC, sneurlax commented on lib/pages/settings_views/global_settings_view/manage_nodes_views/add_edit_node_view.dart
> +    } else if (coin is Mimblewimblecoin) {
Resolved by aaba3cf9372c0dacd29e1b213d79971622e449b5 but not on this remote.

2025-09-03 18:06 UTC, merged

2025-09-04 03:17 UTC, sneurlax commented
I force pushed a reversion of this merge but can't re-open the PR, sorry.  See https://github.com/cypherstack/stack_wallet/compare/mwc...vekamo:stack_wallet:mwc-integration