feat: wrap with semantic widget for talkback
cypherstack/stack_wallet pull request #505
Opened 2023-04-27 18:34 UTC by detherminal

This pr implements wrapping buttons and so many other widgets with semantic widget for talkback and labels them.

Closes #500

2023-04-27 19:44 UTC, julian-CStack commented
Looks good to me. My only suggestion would be to use a more descriptive name such as `semanticsLabel` instead of `label` for custom widgets that pass the semantics label through such as https://github.com/cypherstack/stack_wallet/pull/505/files#diff-9ebb9d922fa60af59c78a62c8eefefcf143478c873c1cfca2fccfca1d1fdc3aeR69

2023-04-27 19:55 UTC, sneurlax commented on lib/pages/receive_view/receive_view.dart
> +                  label: "Adress List Pop-up Button. Opens A Pop-up For Adress List Button.",
Spelling: "Address"

2023-04-27 20:00 UTC, sneurlax requested changes
LGTM, besides some spelling mistakes: "Openes" (Opens) and "Adresses" (Addresses).  Not sure if every word needs to be capitalized for talkback or if it matters (would it ever be seen?)

Does this close all of the examples in #500, most, some, etc?  We can merge this is and have a tester tap through for a list of everything we might want talkback on?

Tests just need to be rerun on our side with our secrets.  I can merge your staging to cypherstack:stack_wallet#detherminal and we can PR that to staging to (probably) pass tests

2023-04-28 18:23 UTC, detherminal commented
Hey @sneurlax I changed ```label```s to ```semanticsLabel```s and corrected misspelling. You might want to check it out.

2023-05-01 19:49 UTC, julian-CStack approved these changes

2023-05-02 22:44 UTC, sneurlax approved these changes
Approved, I just don't know if it addresses *every* button/widget listed in the issue

2023-05-02 22:44 UTC, merged