Windows Flutter build updates
cypherstack/stack_wallet pull request #578
Opened 2023-06-06 22:39 UTC by danrmiller

Uncomment downloading flutter windows SDK and fetch version 3.10.3 instead of 3.7.12.

2023-06-09 18:06 UTC, sneurlax approved these changes

2023-08-05 02:37 UTC, sneurlax requested changes
since this submission, we've moved on from 3.10.3 to 3.10.6

we should test this on Windows sometime

2023-08-05 02:37 UTC, sneurlax commented on scripts/windows/deps.ps1
> +$FLUTTER_SDK_URL = "https://storage.googleapis.com/flutter_infra_release/releases/stable/windows/flutter_windows_3.10.3-stable.zip"
we're on 3.10.6 now but otherwise I'd use this updated script for windows dev setup

2023-12-12 19:15 UTC, sneurlax commented
We are now on Flutter 3.13.0.

2024-01-29 19:36 UTC, sneurlax commented
We're now on Flutter 3.16.0

2024-04-03 23:27 UTC, sneurlax commented
See https://github.com/cypherstack/stack_wallet/pull/800/files#diff-9d87e8f7634435500e079b2c1df3fbedf1ab06de98a395fdf1722d69e837fb58 for an update to 3.16.0

2024-05-09 04:07 UTC, danrmiller commented
stale

2024-05-09 04:07 UTC, closed without merging