Add Tor client to Stack Wallet
cypherstack/stack_wallet pull request #664
Opened 2023-09-09 03:24 UTC by sneurlax

This PR adds an experimental Tor client to Stack Wallet

It uses Arti, the Tor Project's new client written in Rust

It is also compatible with the old C-based Tor if backwards compatibility is needed

![Screenshot from 2023-09-07 18-25-42](https://github.com/cypherstack/stack_wallet/assets/4107993/0df7235f-2dd9-49c0-a866-09ef8b28e257)
![Screenshot from 2023-09-07 18-28-01](https://github.com/cypherstack/stack_wallet/assets/4107993/2775447f-5265-4d36-a044-7f65797cdb7d)
![Screenshot from 2023-09-07 18-27-51](https://github.com/cypherstack/stack_wallet/assets/4107993/4aba4dfa-b143-4598-8cc2-0d7f4f90f3ff)

![Screenshot from 2023-09-08 16-27-09](https://github.com/cypherstack/stack_wallet/assets/4107993/0f3a010a-5961-41d0-a6f2-b808c2f6d43c)
![Screenshot from 2023-09-08 16-27-13](https://github.com/cypherstack/stack_wallet/assets/4107993/5123dea8-a0e2-4815-b6dc-ccd81cd51c9e)
![Screenshot from 2023-09-08 16-27-32](https://github.com/cypherstack/stack_wallet/assets/4107993/7bd0acca-3a47-40b2-ba10-c2b45e786ea8)

2023-09-18 18:19 UTC, sneurlax commented
Closing this to stop running tasks, but I'll edit the top post with tasks for merging this in.

2023-09-20 03:19 UTC, sneurlax commented on .gitignore
> +tor_logs.txt
These last two lines added to .gitignore could be left off

2023-09-20 03:21 UTC, sneurlax commented on .gitmodules
What even is this change?

2023-09-20 03:22 UTC, sneurlax commented on lib/electrumx_rpc/cached_electrumx.dart
I forget why these firo-related changes aren't in staging already

2023-09-20 03:29 UTC, sneurlax commented on lib/networking/socks_socket.dart
This could be spun out into its own package.

2023-09-20 03:32 UTC, sneurlax commented on lib/networking/socks_socket.dart
> +        // TODO make sure sending error as string is acceptable.
How would we test if Stack (or Stack's tor?) can or can't handle strings?

2023-09-20 03:34 UTC, sneurlax commented on lib/networking/socks_socket.dart
> +  Future<void> connect() async {
connect doesn't return.

2023-09-20 03:39 UTC, sneurlax commented on lib/networking/socks_socket.dart
> +    }
OK, if `sslEnabled` then `_subscription = _secureSocksSocket.listen(`, but what about non-SSL connections?

We still need to `_subscription = _socksSocket.listen(` for non-SSL connections, right?

2023-09-20 03:45 UTC, sneurlax commented on lib/networking/socks_socket.dart
> +  Future<void> sendServerFeaturesCommand() async {
This should probably be moved to the bottom of the class.  It isn't used except by an example in another repository...  It should've been moved into the tor package and used through that

2023-09-20 03:46 UTC, sneurlax commented on lib/networking/socks_socket.dart
This should be spun out into its own package and/or put into and used through the tor / tor_ffi_plugin package.

2023-09-20 03:47 UTC, sneurlax commented on lib/pages/exchange_view/exchange_coin_selection/exchange_currency_selection_view.dart
> +import '../../../services/exchange/exchange.dart';
This should use a package import

2023-09-20 03:49 UTC, sneurlax commented on lib/pages/ordinals/ordinal_details_view.dart
> +      throw Exception("statusCode=${response.code} body=${response.bodyBytes}");
`throw Exception("OrdinalDetailsView _savePngToFile statusCode=${response.code} body=${response.bodyBytes}");`

2023-09-20 03:52 UTC, sneurlax commented on lib/pages/settings_views/wallet_settings_view/wallet_settings_view.dart
Do we intend to remove firo cache-clearing here?

2023-09-20 03:53 UTC, sneurlax commented on lib/pages/wallet_view/transaction_views/transaction_details_view.dart
> +    print("THIS TRANSACTION IS $_transaction");
no prints in prod :)

2023-09-20 04:54 UTC, sneurlax commented on pubspec.lock
Should we limit these pubspec.lock changes?  I `flutter upgrade`d to refresh my tor_ffi_plugin (cypherstack/tor) package (which I updated to export SOCKSSocket and return from connect)

2023-09-20 17:42 UTC, julian-CStack requested changes

2023-09-20 18:21 UTC, sneurlax commented on lib/pages/wallet_view/sub_widgets/tx_icon.dart
Resolved by https://github.com/cypherstack/stack_wallet/pull/664/commits/8d6c355b9598f360a6c623d062405d1e5f9e9b2b

2023-09-20 18:41 UTC, sneurlax commented on windows/flutter/generated_plugins.cmake
Yes, and these additional changes are also needed: https://github.com/cypherstack/stack_wallet/pull/664/commits/cd00e9f8fd6bfe085dbe85d920ca6eca61230751

2023-09-20 21:04 UTC, merged